# Generated by Django 4.2.5 on 2023-09-18 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table8', '0003_utp_rejected2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utp',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='utp', to=settings.AUTH_USER_MODEL),
        ),
    ]
