# Generated by Django 4.2.4 on 2023-09-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_TDO',
            new_name='is_HOT',
        ),
    ]
