# Generated by Django 4.2.4 on 2023-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_areamanager_alter_user_is_cdn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default2.png', upload_to=''),
        ),
    ]
