# Generated by Django 4.2.5 on 2023-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_TDO',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
