# Generated by Django 4.2.4 on 2023-09-03 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('Area_Office', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('CCN', models.CharField(blank=True, max_length=255)),
                ('NHT', models.IntegerField(blank=True, default=0)),
                ('Designation', models.CharField(blank=True, max_length=255)),
                ('NAM', models.CharField(blank=True, max_length=255)),
                ('Designation1', models.CharField(blank=True, max_length=255)),
                ('Date', models.CharField(blank=True, max_length=255)),
                ('Month_of_report', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
