# Generated by Django 4.2.4 on 2023-09-03 20:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('Department', models.CharField(blank=True, max_length=255)),
                ('Directors_name', models.CharField(blank=True, max_length=255)),
                ('Team_leader', models.CharField(blank=True, max_length=255)),
                ('Number_of_TDOS_Department', models.IntegerField(default=0)),
                ('Month_of_Report', models.CharField(blank=True, default=datetime.datetime(2023, 9, 3, 20, 58, 54, 250064, tzinfo=datetime.timezone.utc), max_length=50)),
                ('Division', models.CharField(blank=True, max_length=255)),
                ('Number_of_TDOS_Team', models.IntegerField(default=0)),
                ('Deignation', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, default=datetime.datetime(2023, 9, 3, 20, 58, 54, 250064, tzinfo=datetime.timezone.utc), max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
