# Generated by Django 4.2.4 on 2023-09-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table1', '0014_rename_verified_basicform_verified_cpd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicform',
            old_name='verified_cpd',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='basicform',
            name='Month_of_Report',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 9, 14, 12, 12, 59, 256865, tzinfo=datetime.timezone.utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='basicform',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 9, 14, 12, 12, 59, 256865, tzinfo=datetime.timezone.utc), max_length=50),
        ),
    ]
