# Generated by Django 4.2.5 on 2023-09-18 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table1', '0022_alter_basicform_month_of_report_alter_basicform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='Month_of_Report',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 9, 18, 7, 15, 5, 96308, tzinfo=datetime.timezone.utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='basicform',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 9, 18, 7, 15, 5, 96308, tzinfo=datetime.timezone.utc), max_length=50),
        ),
    ]
