# Generated by Django 4.2.4 on 2023-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table6', '0002_alter_dtpa_achieve_per_alter_dtpa_monthly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtpa',
            name='name',
        ),
        migrations.AddField(
            model_name='dtpa',
            name='AGTP',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='NTAC',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='NTPD',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='NTPI',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='NTPS',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='achieve_per2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='achieve_per3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='achieve_per4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='achieve_per5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='monthly2',
            field=models.CharField(default='september', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='monthly3',
            field=models.CharField(default='september', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='monthly4',
            field=models.CharField(default='september', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='monthly5',
            field=models.CharField(default='september', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='remarks2',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='remarks3',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='remarks4',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='remarks5',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='target',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='target2',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='target3',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='target4',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='target5',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='dtpa',
            name='monthly',
            field=models.CharField(default='september', max_length=50),
        ),
        migrations.AlterField(
            model_name='dtpa',
            name='remarks',
            field=models.CharField(default='Good', max_length=50),
        ),
    ]
