# Generated by Django 4.2.4 on 2023-09-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table6', '0003_remove_dtpa_name_dtpa_agtp_dtpa_ntac_dtpa_ntpd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtpa',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='verified_hot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dtpa',
            name='verified_manager',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
