# Generated by Django 4.2.5 on 2023-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table6', '0004_dtpa_approved_dtpa_rejected_dtpa_verified_hot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtpa',
            name='rejected2',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
