# Generated by Django 4.2.4 on 2023-09-03 20:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2023, 9, 3, 20, 58, 54, 250064, tzinfo=datetime.timezone.utc))),
                ('no_org', models.IntegerField()),
                ('no_part', models.IntegerField()),
                ('course_fee', models.IntegerField()),
                ('ammount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
