# Generated by Django 4.2.4 on 2023-09-07 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stp',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 7, 21, 28, 7, 869635, tzinfo=datetime.timezone.utc)),
        ),
    ]
