# Generated by Django 4.2.4 on 2023-09-14 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table5', '0012_alter_stp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stp',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 11, 13, 13, 403485, tzinfo=datetime.timezone.utc)),
        ),
    ]
