# Generated by Django 4.2.4 on 2023-09-14 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table5', '0016_alter_stp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stp',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 12, 48, 55, 692711, tzinfo=datetime.timezone.utc)),
        ),
    ]
