# Generated by Django 4.2.4 on 2023-09-15 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table5', '0017_alter_stp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stp',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='stp',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='stp',
            name='verified_hot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='stp',
            name='verified_manager',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stp',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 21, 37, 50, 699948, tzinfo=datetime.timezone.utc)),
        ),
    ]
