# Generated by Django 4.2.5 on 2023-09-18 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table5', '0018_stp_approved_stp_rejected_stp_verified_hot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stp',
            name='rejected2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stp',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 5, 1, 29, 915783, tzinfo=datetime.timezone.utc)),
        ),
    ]
