# Generated by Django 4.2.5 on 2023-09-18 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table5', '0019_stp_rejected2_alter_stp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stp',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 6, 35, 7, 798060, tzinfo=datetime.timezone.utc)),
        ),
    ]
